[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
spl_staking_project = "BxnKuUL7pbhBgKbTaamn7qPgPtwaxHx6hJgDNoxhHjP2"

[registry]
url = "https://api.mainnet.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/home/vaibhav/Documents/wallets-json/ubaid-keypair_tokenStake.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
